--Nome: Ana Lucia dos Santos
--Nome: Beatriz Alves Fonseca
--Nome: Rodrigo Monteiro Mariano

--Turma: Análise e Desenvolvimento de Sistemas
--Matéria: Laboratório de Engenharia de Software
--Período: Manhã

--Professora: Sávio

--Tabela USUARIO
CREATE TABLE USUARIO (
	USER_ID NUMBER(10) CONSTRAINT PK_USER_ID PRIMARY KEY,
	USER_NOME TEXT,
	USER_SOBRENOME TEXT,
	USER_RG CHAR(11),
	USER_CPF CHAR(11),
	USER_SENHA TEXT,
	USER_EMAIL TEXT,
	USER_RUA TEXT,
	USER_CIDADE TEXT,
	USER_ESTADO TEXT,
	USER_TELEFONE CHAR(9)
);

--Tabela ITEM
CREATE TABLE ITEM (
	ITEM_ID NUMBER(10) CONSTRAINT PK_ITEM_ID PRIMARY KEY,
	ITEM_TITULO TEXT,
	ITEM_ID_USUARIO NUMBER(10),
	ITEM_ID_TIPO NUMBER(10),
	ITEM_ID_ESTADO NUMBER(10),
	ITEM_TROCA CHAR(1) CONSTRAINT CH_ITEM_TROCA CHECK(ITEM_TROCA IN('V','F')),
	ITEM_PRECO NUMBER(10,2),
	ITEM_DESCRICAO TEXT,
	ITEM_COMPRA CHAR(1) CONSTRAINT CH_ITEM_TROCA CHECK(ITEM_TROCA IN('V','F')),
);

--Tabela TIPO
CREATE TABLE TIPO (
	TIPO_ID NUMBER(10) CONSTRAINT PK_ITEM_ID PRIMARY KEY,
	TIPO_DESCRICAO
);

--Tabela ESTADO
CREATE TABLE ESTADO (
	ESTADO_ID NUMBER(10) CONSTRAINT PK_ESTADO_ID PRIMARY KEY,
	ESTADO_DESCRICAO
);
--Tabela NEGOCIACAO
CREATE TABLE NEGOCIACAO (
	NEG_ID NUMBER(10) CONSTRAINT PK_NEG_ID PRIMARY KEY,
	NEG_TIPO TEXT,
	NEG_ID_USER NUMBER(10),
	NEG_ID_ITEM NUMBER(10)
);

--Alteração tabela ITEM
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_TIPO) REFERENCES TIPO (TIPO_ID);
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_ESTADO) REFERENCES ESTADO (ESTADO_ID);
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_USUARIO) REFERENCES USUARIO (USUARIO_ID);

--Alteração tabela NEGOCIACAO
ALTER TABLE NEGOCIACAO ADD FOREIGN KEY(NEG_ID_USER) REFERENCES USER (USER_ID);
ALTER TABLE NEGOCIACAO ADD FOREIGN KEY(NEG_ID_ITEM) REFERENCES ITEM (ITEM_ID);