--Nome: Ana Lucia dos Santos
--Nome: Beatriz Alves Fonseca
--Nome: Rodrigo Monteiro Mariano

--Turma: Análise e Desenvolvimento de Sistemas
--Matéria: Laboratório de Engenharia de Software
--Período: Manhã

--Professor: Sávio Carvalho

--Tabela USUARIO
CREATE TABLE USUARIO (
    USER_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    USER_NOME VARCHAR(85),
    USER_SOBRENOME VARCHAR(85),
    USER_RG CHAR(11),
    USER_CPF CHAR(11),
    USER_SENHA VARCHAR(85),
    USER_EMAIL VARCHAR(85),
    USER_RUA VARCHAR(85),
    USER_CIDADE VARCHAR(85),
    USER_ESTADO CHAR(2),
    USER_TELEFONE CHAR(9)
);

--Tabela ITEM
CREATE TABLE ITEM (
	ITEM_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	ITEM_TITULO VARCHAR(85),
	ITEM_ID_USUARIO INT(10),
	ITEM_ID_TIPO INT(10),
	ITEM_ID_ESTADO INT(10),
	ITEM_TROCA BOOLEAN,
	ITEM_PRECO DOUBLE,
	ITEM_DESCRICAO VARCHAR(85),
	ITEM_COMPRA BOOLEAN
);

--Tabela TIPO
CREATE TABLE TIPO (
	TIPO_ID INT(10) PRIMARY KEY AUTO_INCREMENT
);

--Tabela ESTADO
CREATE TABLE ESTADO (
	ESTADO_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	ESTADO_DESCRICAO VARCHAR(85)
);
--Tabela NEGOCIACAO
CREATE TABLE NEGOCIACAO (
	NEG_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	NEG_TIPO VARCHAR(85),
	NEG_ID_USER INT(10),
	NEG_ID_ITEM INT(10)
);

--Alteração tabela ITEM
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_TIPO) REFERENCES TIPO (TIPO_ID);
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_ESTADO) REFERENCES ESTADO (ESTADO_ID);
ALTER TABLE ITEM ADD FOREIGN KEY(ITEM_ID_USUARIO) REFERENCES USUARIO (USER_ID);

--Alteração tabela NEGOCIACAO
ALTER TABLE NEGOCIACAO ADD FOREIGN KEY(NEG_ID_USER) REFERENCES USUARIO (USER_ID);
ALTER TABLE NEGOCIACAO ADD FOREIGN KEY(NEG_ID_ITEM) REFERENCES ITEM (ITEM_ID);

--Alteração tabela TIPO
ALTER TABLE TIPO ADD TIPO_DESCRICAO VARCHAR(85);








